### ISSUE TITLE
about calculating train error and test error when use two gpus

### ISSUE THREAD

**Issue by anthony123** [ppwwyyxx/tensorpack#545]
this is the code of get_config() function:

```
    batch_size  /= len(nr_tower)

    callbacks = []
    callbacks.append(ModelSaver())
    nr_tower = len(args.gpu.split(','))
    if nr_tower == 1:
        # single-GPU inference with queue prefetch
        callbacks.append(InferenceRunner(dataset_test,
                [ScalarStats('cost'), ClassificationError()]))
    else:
        # multi-GPU inference (with mandatory queue prefetch)
        callbacks.append(DataParallelInferenceRunner(
                dataset_test, [ScalarStats('cost'), ClassificationError()], list(range(nr_tower))))


    callbacks.append(ScheduledHyperParamSetter('learning_rate', [(1, 0.1), (args.drop_1, 0.01), (args.drop_2, 0.001),(args.drop_3, 0.0001)]))
    return TrainConfig(
        dataflow=dataset_train,
        callbacks=callbacks,
        model=Model(args.k, args.num_block, args.layers_per_block, args.path, args.increasing_rate, args.layer_increasing_rate),
        steps_per_epoch=steps_per_epoch,
        max_epoch=args.max_epoch,
        nr_tower=nr_tower,
    )
```

however , the test error is different under two conditions!  the followings is the first epoch results:
 when I use  two gpus:
train_error: 0.18789
validation_cost: 1.1767
 validation_error: 0.1949
wd_cost: 0.60683

when I use one gpu:

 train_error: 0.38656
 validation_cost: 1.9007
 validation_error: 0.3909
 wd_cost: 0.81026

So my question is : What is the right way to calculate train error and validation error when I use two gpus?

**Comment by ppwwyyxx** [comment]
If this is two independent runs, you cannot expect them to have the same results in any case.

Another thing to note is, if you didn't half the batch size correctly you may have trained the dataset twice so you got better results with two gpus.

But there isn't enough information given. You're not using any examples and there is not enough code to tell what happened to you.

**Comment by anthony123** [comment]
firstly, i do half the batch size from 64 to 32 correctly when using two gpus.  

The results are of  the FIRST epoch under two conditions(one gpu & two gpus). When I ran the code twice on one gpu, then the results of The FIRST EPOCH are almost the same. 

All the other codes are the same under one gpu versus two gpus

**Comment by ppwwyyxx** [comment]
I prefer to believe you did something wrong but there is not enough code to tell. And to be honest, there could be many other reasons specific to your task that can cause performance differences.

If you think there is something wrong with `DataParallelInferenceRunner`, the way to test it is to enable both InferenceRunner together and see if they gives consistent results. That's how I tested its correctness.

**Comment by anthony123** [comment]
Is it possible "Pre-filling staging area" affect the result?

 In the line 205 of Inference_runnner.py, it says that "hooks from StagingInput will force the consumption of nr_tower datapoints in every run."

**Comment by ppwwyyxx** [comment]
If your `dataset_test` is a `DataFlow`, it's unrelated to this comment.

**Comment by anthony123** [comment]
When i enable both InferenceRunner and DataParallelInferenceRunner(by pushing both to callbacks), there is only one output. Maybe I do it wrong?

**Comment by ppwwyyxx** [comment]
Because by default they use the same name for logging.

Both `ScalarStats` and `ClassificationError` has options to use a different name. See docs: http://tensorpack.readthedocs.io/en/latest/modules/callbacks.html#tensorpack.callbacks.ScalarStats

**Comment by anthony123** [comment]
The validation(test) error are exactly the same !   I do not think this is right!

**Comment by ppwwyyxx** [comment]
My best guess is you did something wrong with batch size. But again, there is not enough code to tell. You set `batch_size  /= len(nr_tower)` but I don't see where it is used.

**Comment by anthony123** [comment]
I do use it in the get_data() function, codes are as followings:
```
    ds = AugmentImageComponent(ds, augmentors)
    nr_tower = args.gpu.split(',')
    BATCH_SIZE = 64
    BATCH_SIZE  /= len(nr_tower)
    ds = BatchData(ds, BATCH_SIZE, remainder=not isTrain)
    if isTrain:
        ds = PrefetchData(ds, 3, 2)
    return ds

```
The iterations (For one epoch) change from 781 to 1562 for training, change from 157 to 313 for testing(two gpus versus one gpu).

And I find one strange thing, 
```
callbacks.append(DataParallelInferenceRunner(
                dataset_test, [ScalarStats('cost'), ClassificationError()], [0,1,2]))
```
stills work, but I only have two gpus on my computer

**Comment by ppwwyyxx** [comment]
Since batch size is halfed and #GPU is doubled already, steps_per_epoch should be fixed, rather than doubled. Maybe you've missed the doc [here](http://tensorpack.readthedocs.io/en/latest/tutorial/trainer.html#multigpu-trainers).

When you don't have enough devices it will still run. TensorFlow will try to put the graph on existing devices.

**Comment by anthony123** [comment]
So How should I fix the #steps_per_epoch? should I pass 64 as the second param for the BatchData function?

**Comment by ppwwyyxx** [comment]
Keep batch_size (i.e. batch_size_per_gpu) * #GPU * steps_per_epoch unchanged.

**Comment by anthony123** [comment]
I change the code as following:
from 
`steps_per_epoch = dataset_train.size()`
to
`steps_per_epoch = dataset_train.size()//nr_tower`

and pass it to funciton:

```
return TrainConfig(
        dataflow=dataset_train,
        callbacks=callbacks,
        model=Model(args.k, args.num_block, args.layers_per_block, args.path, args.increasing_rate, args.layer_increasing_rate),
        steps_per_epoch=steps_per_epoch,
        max_epoch=args.max_epoch,
        nr_tower=nr_tower,
    )
```
the step is kept the same, but the problem is still there :(

**Comment by ppwwyyxx** [comment]
Again, if these are two independent runs, you cannot expect them to have the same results anyway. There could be many other reasons in your code that cause differences. 

At least I wanted to make sure you're using batch size & steps correctly. On existing examples such as cifar10, when batch size & steps are changed accordingly the performance will be roughly the same.

If you want this to be a bug report you'd better provide more information such as code and instructions and logs. "the problem is still there" isn't helpful at all in solving any problems.

**Comment by anthony123** [comment]
Maybe you can give me your e-mail, and i can send you my code . the code is less than 300 lines

**Comment by ppwwyyxx** [comment]
ppwwyyxxc@gmail.com
code & logs.

**Comment by anthony123** [comment]
Keep steps_per_epoch constant solved my problem. 

change the code
from
`steps_per_epoch = dataset_train.size()`
to
`steps_per_epoch = dataset_train.size()//nr_tower`
